### ISSUE TITLE
How to modify interval time

### ISSUE THREAD

**Issue by cesalo** [pedrocesar-ti/internet-speedtest-docker#10]
Hi - Great work with the app. I installed it as per the instructions and is working great but the interval is at 20 seconds and I'd like to change it to 5m or so.
Can you elaborate about how to do that? I saw the comment about the variable interval_time but not sure how to use it.
Thanks.

**Comment by pedrocesar-ti** [comment]
I can see the confusion, the documentation doesn't state correctly how the test run and I'll fix that.

Basically, the speedtest (for Download and Upload takes around 30 seconds to run, at least on my case) and on top of that there is a sleep time where we can define the period between one test and another, this period is defined via variable **TEST_INTERVAL** (in seconds) and the actual default time at the moment is 5 seconds, defined at the _env/testing.env_ file.

So to be able to run your test every 5m you just need to update the variable  **TEST_INTERVAL** in the _env/testing.env_ file to 300 and that should work:

`TEST_INTERVAL=300`

* Just bear in mind that the speed test execution time will be added on top of the test interval so you might end up with data points every 5 minutes and something.

**Comment by cesalo** [comment]
Made the change and restarted the 3 docker instances but still see in the graphic that is running every 20 seconds or so:
![image](https://user-images.githubusercontent.com/16859916/57168148-927f0800-6dce-11e9-9aa4-d252483a82ac.png)
Checking the docker-compose.yml:
```
cat docker-compose.yml
---
version: '2'
services:
  db:
    image: influxdb 
    container_name: influxdb
    volumes:
      - "/home/plex/internet-speedtest-docker/influxdb/:/var/lib/influxdb"
    ports:
      - "8084:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
  web:
    image: pedrocesarti/internet-speedtest-docker:grafana 
    container_name: speedweb
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    image: pedrocesarti/internet-speedtest-docker:speedtest
    container_name: speedtest
    links:
      - db:db
    env_file:
      - ./env/testing.env
```

Should I add a volume in the service "testing"? at the moment the volume is just defined for the service "db". Otherwise not sure why the change did't change the interval of snapshots.
