### ISSUE TITLE
Error on Rapsberry PI

### ISSUE THREAD

**Issue by sebastienhouzet** [pedrocesar-ti/internet-speedtest-docker#9]
Hello

Error on raspberry PI : Docker version 18.09.0, build 4d60db4

root@pihome:/home/pi/internet-speedtest-docker# docker-compose up -d
Unable to find image 'docker/compose:1.23.2' locally
1.23.2: Pulling from docker/compose
4fe2ade4980c: Pull complete
658ccff8d4f1: Pull complete
71166c3c8d42: Pull complete
c246ed86dd59: Pull complete
Digest: sha256:f6e4963cd17f709fb57f7cf0842e269ed6ba173c3490055b50c701a257feb860
Status: Downloaded newer image for docker/compose:1.23.2

**standard_init_linux.go:207: exec user process caused "exec format error"**

**Comment by pedrocesar-ti** [comment]
Hello @sebastienhouzet 
 I'm sorry for leaving this issue open for too long. But took me quite a while to figure out an environment to test this.

Can you please tell me if you still having this issue, if yes, I now can test it and fix it.

Cheers.

**Comment by pedrocesar-ti** [comment]
I have changed the base container images to upgrade the tools but still a small issue with the automatic build on DockerHub so the best way to run on your Raspberry Pi is to BUILD the image locally with docker-compose.

Your docker-compose.yml should look like this:
```
---
version: '2'
services:
  db:
    image: influxdb
    container_name: influxdb
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
  web:
    build: ./speedweb
    container_name: speedweb
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    build: ./speedtest
    container_name: speedtest
    links:
      - db:db
    env_file:
      - ./env/testing.env
```
